bases:
  - ../base
patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: giggle-api
    path: ingress_patch.yaml
  - target:
      group: apps
        version: v1
        kind: Deployment
        name: giggle-api
        path: image_tag_patch.yaml
